# Tells Docker to use Node.js version 18
FROM node:18
# Set working directory inside the container
WORKDIR /app
# Copy package.json and package-lock.json
copy package*.json ./
# Install dependencies
RUN npm install
# Copy all source code into the container
COPY . .
#  Expose port your Express app 
EXPOSE 4002
# Start the server
CMD ["node","index.js"]